import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { defineCommand } from "citty";
import { join, resolve } from "pathe";
import type { CommandLifecycle } from "../docs/lifecycle-types";
import { ZikuError } from "../errors";
import { checkRepoExists, getGitHubToken, createPullRequest } from "../utils/github";
import { detectGitHubOwner, DEFAULT_TEMPLATE_REPO } from "../utils/git-remote";
import { ZIKU_CONFIG_FILE, generateZikuJsonc } from "../utils/ziku-config";
import { confirmAction } from "../ui/prompts";
import { intro, log, outro, pc } from "../ui/renderer";

// ビルド時に置換される定数
declare const __VERSION__: string;
const version = typeof __VERSION__ !== "undefined" ? __VERSION__ : "dev";

/**
 * setup コマンドのファイル操作メタデータ。
 * テンプレートリポジトリに .ziku/ziku.jsonc を作成する。
 */
export const setupLifecycle: CommandLifecycle = {
  name: "setup",
  description: "テンプレートリポジトリの初期化",
  ops: [
    {
      file: ZIKU_CONFIG_FILE,
      location: "template",
      op: "create",
      note: "デフォルト include パターンで生成（既存ならスキップ）",
    },
  ],
};

/**
 * AI agent の設定共有を主な用途として想定したデフォルト include パターン。
 * Claude Code のルール・スキル・フック、MCP 設定、開発環境設定をカバーする。
 */
const DEFAULT_INCLUDE_PATTERNS: string[] = [
  ".claude/settings.json",
  ".claude/rules/*.md",
  ".claude/skills/**",
  ".claude/hooks/**",
  ".mcp.json",
  ".devcontainer/**",
  ".github/**",
];

export const setupCommand = defineCommand({
  meta: {
    name: "setup",
    version,
    description: "Initialize a template repository with .ziku/ziku.jsonc",
  },
  args: {
    dir: {
      type: "positional",
      description: "Template repository directory",
      default: ".",
    },
    remote: {
      type: "boolean",
      description: "Create a PR to set up a remote template repository instead of local",
      default: false,
    },
    from: {
      type: "string",
      description: "Remote template repository as owner/repo (used with --remote)",
    },
  },
  async run({ args }) {
    intro("setup");

    if (args.remote) {
      await handleRemoteSetup(args.from as string | undefined);
      return;
    }

    const targetDir = resolve(args.dir);
    handleLocalSetup(targetDir);
  },
});

/**
 * ローカルのテンプレートリポジトリに .ziku/ziku.jsonc を作成する。
 *
 * テンプレートリポジトリのルートで `ziku setup` を実行した場合の処理。
 * ziku.jsonc が既にあればスキップ。
 */
function handleLocalSetup(targetDir: string): void {
  log.info(`Target: ${pc.cyan(targetDir)}`);

  const configPath = join(targetDir, ZIKU_CONFIG_FILE);
  if (existsSync(configPath)) {
    log.success(".ziku/ziku.jsonc already exists");
    outro("Template repository is already configured.");
    return;
  }

  log.step("Generating .ziku/ziku.jsonc...");

  const content = generateZikuJsonc({
    include: DEFAULT_INCLUDE_PATTERNS,
    exclude: [],
  });
  const zikuDir = join(targetDir, ".ziku");
  if (!existsSync(zikuDir)) {
    mkdirSync(zikuDir, { recursive: true });
  }
  writeFileSync(configPath, content);

  log.success("Created .ziku/ziku.jsonc");

  outro(
    [
      "Template initialized!",
      "",
      pc.bold("Next steps:"),
      `  ${pc.cyan("1.")} Review and customize ${pc.dim(".ziku/ziku.jsonc")}`,
      `  ${pc.cyan("2.")} ${pc.cyan("git add .ziku/ && git commit -m 'chore: add ziku config'")}`,
      `  ${pc.dim("Then other projects can use this template with")} ${pc.cyan("npx ziku init")}`,
    ].join("\n"),
  );
}

/**
 * リモートのテンプレートリポジトリに ziku.jsonc を追加する PR を作成する。
 */
async function handleRemoteSetup(from: string | undefined): Promise<void> {
  const { owner, repo } = resolveRemoteTarget(from);

  log.info(`Template: ${pc.cyan(`${owner}/${repo}`)}`);

  const exists = await checkRepoExists(owner, repo);
  if (!exists) {
    throw new ZikuError(
      `Repository ${owner}/${repo} not found`,
      "Check the --from value or create the repository first",
    );
  }

  const confirmed = await confirmAction(
    `Create a PR to add .ziku/ziku.jsonc to ${owner}/${repo}?`,
    { initialValue: true },
  );
  if (!confirmed) {
    log.info("Cancelled.");
    return;
  }

  const token = getGitHubToken();
  if (!token) {
    throw new ZikuError(
      "GitHub token required to create a PR",
      "Set GITHUB_TOKEN or GH_TOKEN, or run: gh auth login",
    );
  }

  const content = generateZikuJsonc({
    include: DEFAULT_INCLUDE_PATTERNS,
    exclude: [],
  });

  log.step(`Creating PR to add .ziku/ziku.jsonc to ${pc.cyan(`${owner}/${repo}`)}...`);
  const result = await createPullRequest(token, {
    owner,
    repo,
    files: [{ path: ZIKU_CONFIG_FILE, content }],
    title: "chore: add .ziku/ziku.jsonc for ziku",
    body: `## Summary\n\nAdd \`.ziku/ziku.jsonc\` to enable ziku template management.\n\nThis file defines the include/exclude patterns that ziku tracks for\nbi-directional synchronization between this template and downstream projects.\n\n---\nGenerated by [ziku](https://github.com/tktcorporation/ziku)\n`,
  });
  log.success(`Created PR: ${pc.cyan(result.url)}`);

  outro(
    [
      "PR created!",
      "",
      pc.bold("Next steps:"),
      `  ${pc.cyan("1.")} Review and merge the PR: ${pc.dim(result.url)}`,
      `  ${pc.cyan("2.")} Then run ${pc.cyan("npx ziku init")} in your project`,
    ].join("\n"),
  );
}

/**
 * --from 引数またはgit remoteからリモートテンプレートのowner/repoを解決する。
 */
function resolveRemoteTarget(from: string | undefined): { owner: string; repo: string } {
  if (from) {
    const slashIndex = from.indexOf("/");
    if (slashIndex === -1) {
      return { owner: from, repo: DEFAULT_TEMPLATE_REPO };
    }
    return { owner: from.slice(0, slashIndex), repo: from.slice(slashIndex + 1) };
  }

  const detectedOwner = detectGitHubOwner();
  if (detectedOwner) {
    return { owner: detectedOwner, repo: DEFAULT_TEMPLATE_REPO };
  }

  throw new ZikuError(
    "Cannot detect template source",
    "Specify --from <owner> or --from <owner/repo>",
  );
}
