import { Octokit } from "@octokit/rest";
import { Effect, Option } from "effect";
import { ZikuError } from "../errors";
import type { PrResult } from "../modules/schemas";

export interface PushOptions {
  owner: string;
  repo: string;
  files: Array<{ path: string; content: string }>;
  /** テンプレートから削除するファイル（PR にファイル削除コミットを含める） */
  deletions?: Array<{ path: string }>;
  title: string;
  body?: string;
  baseBranch?: string;
}

/**
 * GitHub API を使って PR を作成
 */
export async function createPullRequest(token: string, options: PushOptions): Promise<PrResult> {
  const octokit = new Octokit({ auth: token });
  const { owner, repo, files, title, body, baseBranch = "main" } = options;

  // 1. 認証ユーザー情報を取得
  const { data: user } = await octokit.users.getAuthenticated();
  const forkOwner = user.login;

  // 2. fork を確認・作成
  const forkRepo = await Effect.runPromise(
    Effect.tryPromise(() => octokit.repos.get({ owner: forkOwner, repo })).pipe(
      Effect.map(({ data }) => data.name),
      Effect.orElse(() =>
        Effect.tryPromise(() => octokit.repos.createFork({ owner, repo })).pipe(
          Effect.tap(() => Effect.promise(() => sleep(3000))),
          Effect.map(({ data }) => data.name),
        ),
      ),
    ),
  );

  // 3. ベースブランチの最新コミット SHA を取得
  const { data: baseBranchRef } = await octokit.repos.getBranch({
    owner,
    repo,
    branch: baseBranch,
  });
  const baseSha = baseBranchRef.commit.sha;

  // 4. 新しいブランチ名を生成
  const branchName = `ziku-sync-${Date.now()}`;

  // 5. fork に新しいブランチを作成
  await octokit.git.createRef({
    owner: forkOwner,
    repo: forkRepo,
    ref: `refs/heads/${branchName}`,
    sha: baseSha,
  });

  // 6. 既存ファイルの SHA を一括取得
  //    getContent を個別に呼ぶと、未存在ファイルで 404 レスポンスが
  //    @octokit/plugin-request-log によりコンソールに出力されるため、
  //    getTree で一括取得して Map で引く。
  const { data: treeData } = await octokit.git.getTree({
    owner: forkOwner,
    repo: forkRepo,
    tree_sha: branchName,
    recursive: "true",
  });
  if (treeData.truncated) {
    throw new Error(
      `Repository tree is too large to fetch entirely. ` +
        `Consider reducing the number of files in ${forkOwner}/${forkRepo}.`,
    );
  }
  const shaMap = new Map<string, string>();
  for (const item of treeData.tree) {
    if (item.type === "blob" && item.sha !== undefined && item.sha !== null && item.path) {
      shaMap.set(item.path, item.sha);
    }
  }

  // 7. ファイルを作成または更新
  for (const file of files) {
    await octokit.repos.createOrUpdateFileContents({
      owner: forkOwner,
      repo: forkRepo,
      path: file.path,
      message: `Update ${file.path}`,
      content: Buffer.from(file.content).toString("base64"),
      branch: branchName,
      sha: shaMap.get(file.path),
    });
  }

  // 7b. ファイルを削除
  if (options.deletions) {
    for (const file of options.deletions) {
      const fileSha = shaMap.get(file.path);
      if (fileSha) {
        await octokit.repos.deleteFile({
          owner: forkOwner,
          repo: forkRepo,
          path: file.path,
          message: `Delete ${file.path}`,
          sha: fileSha,
          branch: branchName,
        });
      }
    }
  }

  // 8. PR を作成
  const { data: pr } = await octokit.pulls.create({
    owner,
    repo,
    title,
    body: body || generatePrBody(files),
    head: `${forkOwner}:${branchName}`,
    base: baseBranch,
  });

  return {
    url: pr.html_url,
    number: pr.number,
    branch: branchName,
  };
}

/**
 * PR の本文を生成
 */
function generatePrBody(files: Array<{ path: string; content: string }>): string {
  const fileList = files.map((f) => `- \`${f.path}\``).join("\n");

  return `## Summary

Auto-generated PR by ziku push command.

## Changed files

${fileList}

---
Generated by [ziku](https://github.com/tktcorporation/.github/tree/main/packages/ziku)
`;
}

/**
 * GitHub トークンを環境変数または gh CLI から取得
 *
 * 優先順位:
 *   1. GITHUB_TOKEN 環境変数
 *   2. GH_TOKEN 環境変数
 *   3. `gh auth token` コマンド出力（gh CLI がインストール済みの場合）
 *
 * 背景: gh CLI でログイン済みなのにトークンを手動入力させるのは不親切。
 * 多くの開発者は `gh auth login` 済みなので、そのトークンを自動取得する。
 */
export function getGitHubToken(): string | undefined {
  const envToken = process.env.GITHUB_TOKEN || process.env.GH_TOKEN;
  if (envToken) return envToken;

  return getGhCliToken();
}

/**
 * gh CLI の `gh auth token` からトークンを取得する。
 * gh CLI が未インストール or 未ログインの場合は undefined を返す。
 */
export function getGhCliToken(): string | undefined {
  return Option.getOrUndefined(
    Effect.runSync(
      Effect.try(() => {
        const { execFileSync } = require("node:child_process");
        return (
          execFileSync("gh", ["auth", "token"], {
            encoding: "utf-8",
            timeout: 5000,
            stdio: ["pipe", "pipe", "pipe"],
          }) as string
        ).trim();
      }).pipe(
        Effect.flatMap((token) =>
          token &&
          (token.startsWith("ghp_") || token.startsWith("gho_") || token.startsWith("github_pat_"))
            ? Effect.succeed(token)
            : Effect.fail("invalid token format" as const),
        ),
        Effect.option,
      ),
    ),
  );
}

/**
 * 認証済み GitHub ユーザーのログイン名を取得する。
 *
 * 背景: テンプレートソースの自動検出で、自分のアカウントの `.ziku` / `.github` リポジトリを
 * 候補に含めるために使用する。トークンがない場合や API エラー時は undefined を返す。
 */
export async function getAuthenticatedUserLogin(): Promise<string | undefined> {
  const token = getGitHubToken();
  if (!token) return undefined;

  return Option.getOrUndefined(
    await Effect.runPromise(
      Effect.tryPromise(async () => {
        const res = await fetch("https://api.github.com/user", {
          headers: { Authorization: `Bearer ${token}` },
        });
        if (!res.ok) return undefined;
        const data = (await res.json()) as { login?: string };
        return data.login;
      }).pipe(Effect.option),
    ),
  );
}

/**
 * GitHub リポジトリの存在確認結果。
 *
 * 背景: 単純な boolean では「確実に存在しない（404）」と「確認不能
 * （レート制限・ネットワーク断・5xx 等）」を区別できず、後者を "not found"
 * と誤判定する問題があった（未認証 API は 60req/h で 403 が返る）。
 * 呼び出し側で match().exhaustive() により網羅的にハンドリングできるよう、
 * 確認結果をタグ付き Union で表現する。
 *
 * ライフサイクル: checkRepoExists が返し、init/setup の解決ロジックで消費される。
 */
export type RepoExistence =
  | { readonly _tag: "Exists" }
  | { readonly _tag: "NotFound" }
  | {
      readonly _tag: "RateLimited";
      /** `x-ratelimit-reset` ヘッダから算出したリセット時刻。取得できなければ undefined */
      readonly resetAt: Date | undefined;
      /** 認証済みトークンで問い合わせたかどうか。エラーメッセージの分岐に使う */
      readonly authenticated: boolean;
    }
  | {
      readonly _tag: "Unknown";
      /** HTTP ステータス。ネットワークエラー等で取得できない場合は undefined */
      readonly status: number | undefined;
      readonly reason: string;
    };

/**
 * GitHub リポジトリの存在を確認する。
 *
 * 背景: ziku init でテンプレートリポジトリが存在しない場合に、giget の
 * エラーメッセージではなく分かりやすいガイダンスを表示するため、
 * 事前にリポジトリの存在をチェックする。HEAD リクエストで軽量に確認。
 *
 * 認証トークンがあれば付与する理由: 未認証 API は 60req/h のレート制限があり、
 * すぐに 403 で弾かれる。また、プライベートリポジトリは未認証だと 404 扱いになる。
 *
 * 戻り値は RepoExistence 型で、各ケース（Exists/NotFound/RateLimited/Unknown）を
 * 呼び出し側が match で網羅的にハンドリングできるようにする。
 */
export function checkRepoExists(owner: string, repo: string): Promise<RepoExistence> {
  const token = getGitHubToken();
  const headers: Record<string, string> = {};
  if (token) {
    headers.Authorization = `Bearer ${token}`;
  }
  return Effect.runPromise(
    Effect.tryPromise({
      try: () =>
        fetch(`https://api.github.com/repos/${owner}/${repo}`, { method: "HEAD", headers }),
      // 明示的に catch を指定しないと Effect.tryPromise は原因を UnknownException で
      // ラップしてしまい、元の Error.message（"Network error" 等）が失われる。
      catch: (cause) => (cause instanceof Error ? cause : new Error(String(cause))),
    }).pipe(
      Effect.map((res): RepoExistence => classifyRepoResponse(res, token !== undefined)),
      Effect.catchAll((cause) =>
        Effect.succeed<RepoExistence>({
          _tag: "Unknown",
          status: undefined,
          reason: cause.message,
        }),
      ),
    ),
  );
}

/**
 * RepoExistence の RateLimited ケースを ZikuError に変換する。
 *
 * 認証状況とリセット時刻を hint に含めることで、ユーザーが
 * 「GITHUB_TOKEN を設定する」か「しばらく待つ」かを判断できる。
 */
export function rateLimitedError(
  r: Extract<RepoExistence, { readonly _tag: "RateLimited" }>,
): ZikuError {
  const base = r.authenticated
    ? "Authenticated quota (5000/hr) exhausted"
    : "Unauthenticated quota (60/hr) exhausted — set GITHUB_TOKEN or run `gh auth login` to raise it to 5000/hr";
  const reset = r.resetAt
    ? ` (resets in ~${Math.max(0, Math.ceil((r.resetAt.getTime() - Date.now()) / 60000))} min)`
    : "";
  return new ZikuError("GitHub API rate limit exceeded", `${base}${reset}`);
}

/**
 * HTTP レスポンスを RepoExistence に分類する。
 *
 * GitHub のレート制限応答は「403 + x-ratelimit-remaining: 0」で判定する。
 * 403 でも二要素認証要求など別原因のケースがあるため、ヘッダで明示的に確認する。
 */
function classifyRepoResponse(res: Response, authenticated: boolean): RepoExistence {
  if (res.ok) return { _tag: "Exists" };
  if (res.status === 404) return { _tag: "NotFound" };
  if (res.status === 403 && res.headers.get("x-ratelimit-remaining") === "0") {
    const resetHeader = res.headers.get("x-ratelimit-reset") ?? "";
    // 数値にパースして有限値でなければ undefined（タイムスタンプ不明）とする。
    const resetEpoch = resetHeader !== "" ? Number(resetHeader) : Number.NaN;
    const resetAt = Number.isFinite(resetEpoch) ? new Date(resetEpoch * 1000) : undefined;
    return { _tag: "RateLimited", resetAt, authenticated };
  }
  return {
    _tag: "Unknown",
    status: res.status,
    reason: res.statusText || `HTTP ${res.status}`,
  };
}

/**
 * テンプレートリポジトリがセットアップ済み（.ziku/ziku.jsonc が存在する）か確認する。
 *
 * 背景: リポジトリが存在しても .ziku/ziku.jsonc がなければテンプレートとして
 * 機能しないため、候補の優先順位付けやユーザーへのヒント表示に利用する。
 * GitHub Contents API で軽量に確認。
 */
export function checkRepoSetup(owner: string, repo: string): Promise<boolean> {
  const token = getGitHubToken();
  const headers: Record<string, string> = {};
  if (token) {
    headers.Authorization = `Bearer ${token}`;
  }
  return Effect.runPromise(
    Effect.tryPromise(() =>
      fetch(`https://api.github.com/repos/${owner}/${repo}/contents/.ziku/ziku.jsonc`, {
        method: "HEAD",
        headers,
      }),
    ).pipe(
      Effect.map((res) => res.ok),
      // ネットワークエラー等の場合は不明として false を返す
      Effect.orElseSucceed(() => false),
    ),
  );
}

/**
 * テンプレートリポジトリを新規作成する。
 *
 * 背景: org に `.github` テンプレートリポジトリが存在しない場合、
 * 空のリポジトリを作成し、README と .ziku/modules.jsonc を初期コミットする。
 */
export async function scaffoldTemplateRepo(
  token: string,
  targetOwner: string,
  targetRepo: string,
): Promise<{ url: string }> {
  const { Octokit: OctokitClient } = await import("@octokit/rest");
  const octokit = new OctokitClient({ auth: token });

  // org か personal かを判定
  const isOrg = await Effect.runPromise(
    Effect.tryPromise(() => octokit.orgs.get({ org: targetOwner })).pipe(
      Effect.map(() => true),
      Effect.orElseSucceed(() => false),
    ),
  );

  // リポジトリを作成
  const createParams = {
    name: targetRepo,
    description: "Dev environment template managed by ziku",
    auto_init: true, // README.md を自動作成
  };

  if (isOrg) {
    const { data: repo } = await octokit.repos.createInOrg({
      org: targetOwner,
      ...createParams,
    });
    return { url: repo.html_url };
  }

  const { data: repo } = await octokit.repos.createForAuthenticatedUser(createParams);
  return { url: repo.html_url };
}

/**
 * テンプレートリポジトリの最新コミット SHA を取得する。
 *
 * 背景: init/pull 時に baseRef として保存し、後で 3-way マージのベース取得に使用する。
 * GitHub API の `Accept: application/vnd.github.sha` を使い、SHA 文字列のみを取得する。
 * 認証不要（公開リポジトリの場合）。
 */
export async function resolveLatestCommitSha(
  owner: string,
  repo: string,
  ref = "main",
): Promise<string | undefined> {
  return Option.getOrUndefined(
    await Effect.runPromise(
      Effect.tryPromise(async () => {
        const url = `https://api.github.com/repos/${owner}/${repo}/commits/${ref}`;
        const res = await fetch(url, {
          headers: { Accept: "application/vnd.github.sha" },
        });
        if (!res.ok) return undefined;
        return (await res.text()).trim();
      }).pipe(Effect.option),
    ),
  );
}

/**
 * sleep utility
 */
function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => {
    setTimeout(resolve, ms);
  });
}
