import { Octokit } from "@octokit/rest";
import type { PrResult } from "../modules/schemas";

export interface PushOptions {
  owner: string;
  repo: string;
  files: Array<{ path: string; content: string }>;
  title: string;
  body?: string;
  baseBranch?: string;
}

/**
 * GitHub API を使って PR を作成
 */
export async function createPullRequest(token: string, options: PushOptions): Promise<PrResult> {
  const octokit = new Octokit({ auth: token });
  const { owner, repo, files, title, body, baseBranch = "main" } = options;

  // 1. 認証ユーザー情報を取得
  const { data: user } = await octokit.users.getAuthenticated();
  const forkOwner = user.login;

  // 2. fork を確認・作成
  let forkRepo: string;
  try {
    const { data: fork } = await octokit.repos.get({
      owner: forkOwner,
      repo,
    });
    forkRepo = fork.name;
  } catch {
    const { data: fork } = await octokit.repos.createFork({
      owner,
      repo,
    });
    forkRepo = fork.name;

    // fork の同期を待つ
    await sleep(3000);
  }

  // 3. ベースブランチの最新コミット SHA を取得
  const { data: baseBranchRef } = await octokit.repos.getBranch({
    owner,
    repo,
    branch: baseBranch,
  });
  const baseSha = baseBranchRef.commit.sha;

  // 4. 新しいブランチ名を生成
  const branchName = `devenv-sync-${Date.now()}`;

  // 5. fork に新しいブランチを作成
  await octokit.git.createRef({
    owner: forkOwner,
    repo: forkRepo,
    ref: `refs/heads/${branchName}`,
    sha: baseSha,
  });

  // 6. ファイルを更新
  for (const file of files) {
    // 既存ファイルの SHA を取得（存在する場合）
    let existingSha: string | undefined;
    try {
      const { data: existingFile } = await octokit.repos.getContent({
        owner: forkOwner,
        repo: forkRepo,
        path: file.path,
        ref: branchName,
      });
      if (!Array.isArray(existingFile) && existingFile.type === "file") {
        existingSha = existingFile.sha;
      }
    } catch {
      // ファイルが存在しない場合は新規作成
    }

    // ファイルを作成または更新
    await octokit.repos.createOrUpdateFileContents({
      owner: forkOwner,
      repo: forkRepo,
      path: file.path,
      message: `Update ${file.path}`,
      content: Buffer.from(file.content).toString("base64"),
      branch: branchName,
      sha: existingSha,
    });
  }

  // 7. PR を作成
  const { data: pr } = await octokit.pulls.create({
    owner,
    repo,
    title,
    body: body || generatePrBody(files),
    head: `${forkOwner}:${branchName}`,
    base: baseBranch,
  });

  return {
    url: pr.html_url,
    number: pr.number,
    branch: branchName,
  };
}

/**
 * PR の本文を生成
 */
function generatePrBody(files: Array<{ path: string; content: string }>): string {
  const fileList = files.map((f) => `- \`${f.path}\``).join("\n");

  return `## Summary

Auto-generated PR by ziku push command.

## Changed files

${fileList}

---
Generated by [ziku](https://github.com/tktcorporation/.github/tree/main/packages/ziku)
`;
}

/**
 * GitHub トークンを環境変数または gh CLI から取得
 *
 * 優先順位:
 *   1. GITHUB_TOKEN 環境変数
 *   2. GH_TOKEN 環境変数
 *   3. `gh auth token` コマンド出力（gh CLI がインストール済みの場合）
 *
 * 背景: gh CLI でログイン済みなのにトークンを手動入力させるのは不親切。
 * 多くの開発者は `gh auth login` 済みなので、そのトークンを自動取得する。
 */
export function getGitHubToken(): string | undefined {
  const envToken = process.env.GITHUB_TOKEN || process.env.GH_TOKEN;
  if (envToken) return envToken;

  return getGhCliToken();
}

/**
 * gh CLI の `gh auth token` からトークンを取得する。
 * gh CLI が未インストール or 未ログインの場合は undefined を返す。
 */
export function getGhCliToken(): string | undefined {
  try {
    const { execSync } = require("node:child_process");
    const token = execSync("gh auth token", {
      encoding: "utf-8",
      timeout: 5000,
      stdio: ["pipe", "pipe", "pipe"],
    }).trim();
    if (
      token &&
      (token.startsWith("ghp_") || token.startsWith("gho_") || token.startsWith("github_pat_"))
    ) {
      return token;
    }
  } catch {
    // gh CLI が未インストール or 未ログイン — 無視
  }
  return undefined;
}

/**
 * GitHub リポジトリの存在を確認する。
 *
 * 背景: ziku init でテンプレートリポジトリが存在しない場合に、
 * giget のエラーメッセージではなく分かりやすいガイダンスを表示するため、
 * 事前にリポジトリの存在をチェックする。
 * 認証不要（公開リポジトリの場合）。HEAD リクエストで軽量に確認。
 */
export async function checkRepoExists(owner: string, repo: string): Promise<boolean> {
  try {
    const url = `https://api.github.com/repos/${owner}/${repo}`;
    const res = await fetch(url, { method: "HEAD" });
    return res.ok;
  } catch {
    // ネットワークエラー等の場合は存在チェックをスキップ（楽観的に続行）
    return true;
  }
}

/**
 * テンプレートリポジトリを新規作成する。
 *
 * 背景: org に `.github` テンプレートリポジトリが存在しない場合、
 * 空のリポジトリを作成し、README と .devenv/modules.jsonc を初期コミットする。
 */
export async function scaffoldTemplateRepo(
  token: string,
  targetOwner: string,
  targetRepo: string,
): Promise<{ url: string }> {
  const { Octokit } = await import("@octokit/rest");
  const octokit = new Octokit({ auth: token });

  // org か personal かを判定
  let isOrg = false;
  try {
    await octokit.orgs.get({ org: targetOwner });
    isOrg = true;
  } catch {
    // personal account
  }

  // リポジトリを作成
  const createParams = {
    name: targetRepo,
    description: "Dev environment template managed by ziku",
    auto_init: true, // README.md を自動作成
  };

  if (isOrg) {
    const { data: repo } = await octokit.repos.createInOrg({
      org: targetOwner,
      ...createParams,
    });
    return { url: repo.html_url };
  }

  const { data: repo } = await octokit.repos.createForAuthenticatedUser(createParams);
  return { url: repo.html_url };
}

/**
 * テンプレートリポジトリに .devenv/modules.jsonc を追加する PR を作成する。
 *
 * 背景: テンプレートリポジトリが存在するが .devenv 構成がない場合、
 * デフォルトのモジュール定義を含む modules.jsonc を PR として提出する。
 */
export async function createDevenvScaffoldPR(
  token: string,
  owner: string,
  repo: string,
  modulesJsoncContent: string,
): Promise<PrResult> {
  return createPullRequest(token, {
    owner,
    repo,
    files: [{ path: ".devenv/modules.jsonc", content: modulesJsoncContent }],
    title: "chore: add .devenv/modules.jsonc for ziku",
    body: `## Summary

Add \`.devenv/modules.jsonc\` to enable ziku template management.

This file defines the modules and file patterns that ziku tracks for
bi-directional synchronization between this template and downstream projects.

---
Generated by [ziku](https://github.com/tktcorporation/ziku)
`,
  });
}

/**
 * テンプレートリポジトリの最新コミット SHA を取得する。
 *
 * 背景: init/pull 時に baseRef として保存し、後で 3-way マージのベース取得に使用する。
 * GitHub API の `Accept: application/vnd.github.sha` を使い、SHA 文字列のみを取得する。
 * 認証不要（公開リポジトリの場合）。
 */
export async function resolveLatestCommitSha(
  owner: string,
  repo: string,
  ref = "main",
): Promise<string | undefined> {
  try {
    const url = `https://api.github.com/repos/${owner}/${repo}/commits/${ref}`;
    const res = await fetch(url, {
      headers: { Accept: "application/vnd.github.sha" },
    });
    if (!res.ok) return undefined;
    return (await res.text()).trim();
  } catch {
    return undefined;
  }
}

/**
 * sleep utility
 */
function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
