/**
 * Agent adapter artifacts を `.claude/` の正本から生成する。
 *
 * 正本:
 *   - hooks: `.claude/hooks/manifest.json`
 *   - rules: `.claude/rules/` 配下の `*.md`（サブディレクトリ含む）
 *
 * 生成物（手編集禁止）:
 *   - `.claude/settings.json` の `hooks` キー
 *   - `.cursor/hooks.json`
 *   - `.codex/hooks.json`
 *   - `.cursor/rules/` 配下の `*.mdc`
 *
 * 使い方:
 *   pnpm agent-adapters:generate
 *   pnpm agent-adapters:check
 */
import { spawnSync } from 'node:child_process';
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '..');
const checkMode = process.argv.includes('--check');

interface RuntimeBinding {
  event: string;
  matcher?: string;
  loopLimit?: null;
}

interface ManifestHook {
  id: string;
  script: string;
  statusMessage?: string;
  claude: RuntimeBinding;
  cursor: RuntimeBinding;
  codex: RuntimeBinding;
}

interface Manifest {
  hooks: ManifestHook[];
}

const GENERATED_HEADER =
  'Generated by `pnpm agent-adapters:generate` from `.claude/` SSOT. Do not edit by hand.';

function readManifest(path: string): Manifest {
  const value: Manifest = JSON.parse(readFileSync(path, 'utf8'));
  return value;
}

function readSettings(path: string): Record<string, unknown> {
  const value: Record<string, unknown> = JSON.parse(readFileSync(path, 'utf8'));
  return value;
}

function writeText(path: string, content: string): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content.endsWith('\n') ? content : `${content}\n`);
}

/** oxfmt が JSON を崩すので、比較・書き込み前に同じ整形を通す */
function formatJsonContent(pathForMessage: string, content: string): string {
  const dir = mkdtempSync(join(tmpdir(), 'agent-adapters-fmt-'));
  const tempPath = join(dir, 'content.json');
  try {
    writeFileSync(tempPath, content.endsWith('\n') ? content : `${content}\n`);
    const result = spawnSync('pnpm', ['exec', 'vp', 'fmt', tempPath], {
      cwd: repoRoot,
      encoding: 'utf8',
    });
    if (result.status !== 0) {
      throw new Error(
        `vp fmt failed for ${pathForMessage}: ${result.stderr || result.stdout || 'unknown error'}`,
      );
    }
    return readFileSync(tempPath, 'utf8');
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

function stableStringify(value: unknown): string {
  return formatJsonContent('json', `${JSON.stringify(value, null, 2)}\n`);
}

function listFiles(dir: string, suffix: string): string[] {
  if (!existsSync(dir)) return [];
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) out.push(...listFiles(full, suffix));
    else if (entry.endsWith(suffix)) out.push(full);
  }
  return out.sort();
}

/** Claude settings.json 用: 同一 event+matcher の hooks をグループ化する */
function buildClaudeHooks(hooks: ManifestHook[]): Record<string, unknown[]> {
  const byEvent = new Map<string, Map<string, ManifestHook[]>>();
  for (const hook of hooks) {
    const eventMap = byEvent.get(hook.claude.event) ?? new Map<string, ManifestHook[]>();
    const matcher = hook.claude.matcher ?? '';
    const list = eventMap.get(matcher) ?? [];
    list.push(hook);
    eventMap.set(matcher, list);
    byEvent.set(hook.claude.event, eventMap);
  }
  const result: Record<string, unknown[]> = {};
  for (const [event, matchers] of byEvent) {
    result[event] = [...matchers.entries()].map(([matcher, group]) => ({
      matcher,
      hooks: group.map((hook) => {
        const entry: Record<string, string> = {
          type: 'command',
          command: `bun "$CLAUDE_PROJECT_DIR"/.claude/hooks/run-or-skip-for-cursor.ts ${hook.script}`,
        };
        if (hook.statusMessage) entry.statusMessage = hook.statusMessage;
        return entry;
      }),
    }));
  }
  return result;
}

function buildCursorHooks(hooks: ManifestHook[]): {
  version: number;
  hooks: Record<string, unknown[]>;
} {
  const byEvent = new Map<string, unknown[]>();
  for (const hook of hooks) {
    const list = byEvent.get(hook.cursor.event) ?? [];
    const entry: Record<string, unknown> = {
      command: `bun .cursor/run-shared-hook.ts ${hook.script}`,
    };
    if (hook.cursor.matcher) entry.matcher = hook.cursor.matcher;
    if ('loopLimit' in hook.cursor) entry.loop_limit = hook.cursor.loopLimit;
    list.push(entry);
    byEvent.set(hook.cursor.event, list);
  }
  return { version: 1, hooks: Object.fromEntries(byEvent) };
}

function buildCodexHooks(hooks: ManifestHook[]): {
  description: string;
  hooks: Record<string, unknown[]>;
} {
  const byEvent = new Map<string, Map<string | undefined, ManifestHook[]>>();
  for (const hook of hooks) {
    const eventMap = byEvent.get(hook.codex.event) ?? new Map<string | undefined, ManifestHook[]>();
    const matcher = hook.codex.matcher;
    const list = eventMap.get(matcher) ?? [];
    list.push(hook);
    eventMap.set(matcher, list);
    byEvent.set(hook.codex.event, eventMap);
  }
  const result: Record<string, unknown[]> = {};
  for (const [event, matchers] of byEvent) {
    result[event] = [...matchers.entries()].map(([matcher, group]) => {
      const block: Record<string, unknown> = {
        hooks: group.map((hook) => {
          const entry: Record<string, string> = {
            type: 'command',
            command: `bun "$(git rev-parse --show-toplevel)/.codex/run-shared-hook.ts" ${hook.script}`,
          };
          if (hook.statusMessage) entry.statusMessage = hook.statusMessage;
          return entry;
        }),
      };
      if (matcher !== undefined) block.matcher = matcher;
      return block;
    });
  }
  return {
    description: 'Codex adapters for the shared hooks maintained under .claude/hooks.',
    hooks: result,
  };
}

/** `.claude/rules/*.md` の paths frontmatter を読む。無ければ alwaysApply。 */
function parseRulePaths(markdown: string): string[] | null {
  if (!markdown.startsWith('---\n')) return null;
  const end = markdown.indexOf('\n---\n', 4);
  if (end === -1) return null;
  const frontmatter = markdown.slice(4, end);
  const inline = frontmatter.match(/^paths:\s*\[([^\]]*)\]/m);
  if (inline) {
    return inline[1]
      .split(',')
      .map((part) => part.trim().replace(/^['"]|['"]$/g, ''))
      .filter(Boolean);
  }
  if (/^paths:\s*$/m.test(frontmatter) || /^paths:\s*\n/m.test(frontmatter)) {
    const lines = frontmatter.split('\n');
    const start = lines.findIndex((line) => /^paths:\s*$/.test(line));
    if (start === -1) return null;
    const paths: string[] = [];
    for (let i = start + 1; i < lines.length; i++) {
      const match = lines[i].match(/^\s*-\s*['"]?([^'"]+)['"]?\s*$/);
      if (!match) break;
      paths.push(match[1]);
    }
    return paths.length > 0 ? paths : null;
  }
  return null;
}

function buildCursorRuleMdc(rulePath: string): { relativePath: string; content: string } {
  const rel = relative(repoRoot, rulePath).replaceAll('\\', '/');
  const markdown = readFileSync(rulePath, 'utf8');
  const paths = parseRulePaths(markdown);
  const title =
    markdown
      .split('\n')
      .find((line) => line.startsWith('# '))
      ?.replace(/^#\s+/, '')
      .trim() ?? relative(join(repoRoot, '.claude/rules'), rulePath);
  const frontmatter =
    paths && paths.length > 0
      ? [
          `---`,
          `description: ${yamlString(`${title} — from ${rel}`)}`,
          `globs: ${yamlString(paths.join(', '))}`,
          `alwaysApply: false`,
          `---`,
          `# ${GENERATED_HEADER}`,
        ].join('\n')
      : [
          `---`,
          `description: ${yamlString(`${title} — from ${rel}`)}`,
          `alwaysApply: true`,
          `---`,
          `# ${GENERATED_HEADER}`,
        ].join('\n');
  const outRel = rel.replace(/^\.claude\/rules\//, '.cursor/rules/').replace(/\.md$/, '.mdc');
  return {
    relativePath: outRel,
    content: `${frontmatter}\n\n@${rel}\n`,
  };
}

function yamlString(value: string): string {
  return JSON.stringify(value);
}

function ensureOrCheck(path: string, next: string): boolean {
  const abs = resolve(repoRoot, path);
  const previous = existsSync(abs) ? readFileSync(abs, 'utf8') : null;
  if (previous === next) return false;
  if (checkMode) {
    console.error(`out of date: ${path}`);
    return true;
  }
  writeText(abs, next);
  console.log(`wrote ${path}`);
  return false;
}

function main(): void {
  const manifest = readManifest(join(repoRoot, '.claude/hooks/manifest.json'));
  if (!Array.isArray(manifest.hooks) || manifest.hooks.length === 0)
    throw new Error('manifest.hooks must be a non-empty array');

  let dirty = false;

  const settingsPath = join(repoRoot, '.claude/settings.json');
  const settings = readSettings(settingsPath);
  settings.hooks = buildClaudeHooks(manifest.hooks);
  dirty = ensureOrCheck('.claude/settings.json', stableStringify(settings)) || dirty;

  dirty =
    ensureOrCheck('.cursor/hooks.json', stableStringify(buildCursorHooks(manifest.hooks))) || dirty;
  dirty =
    ensureOrCheck('.codex/hooks.json', stableStringify(buildCodexHooks(manifest.hooks))) || dirty;

  const ruleFiles = listFiles(join(repoRoot, '.claude/rules'), '.md');
  const generatedRules = ruleFiles.map(buildCursorRuleMdc);
  const expected = new Set(generatedRules.map((rule) => rule.relativePath));

  // 生成対象外の stale .mdc を検出 / 削除（手置きの残骸を残さない）
  const existingMdc = listFiles(join(repoRoot, '.cursor/rules'), '.mdc').map((path) =>
    relative(repoRoot, path).replaceAll('\\', '/'),
  );
  for (const path of existingMdc) {
    if (expected.has(path)) continue;
    if (checkMode) {
      console.error(`unexpected generated rule: ${path}`);
      dirty = true;
      continue;
    }
    rmSync(resolve(repoRoot, path));
    console.log(`removed stale ${path}`);
  }

  for (const rule of generatedRules) {
    dirty = ensureOrCheck(rule.relativePath, rule.content) || dirty;
  }

  if (checkMode && dirty) {
    console.error('Agent adapter artifacts are out of date. Run `pnpm agent-adapters:generate`.');
    process.exit(1);
  }
  if (checkMode) console.log('agent adapter artifacts are up to date');
}

main();
