#!/usr/bin/env pnpm tsx
/**
 * Generate VitePress site pages from README.md
 *
 * README.md はすでに generate-readme.ts でソースコードから自動生成されている。
 * このスクリプトは README.md をパースし、VitePress のページ群と llms.txt を生成する。
 * これにより README ↔ サイト間の二重管理を排除する。
 *
 * Usage:
 *   pnpm run site:generate
 *   pnpm run site:generate --check  # Check only (for CI)
 *
 * Generated files:
 *   - docs/index.md (landing page with VitePress hero)
 *   - docs/guide/getting-started.md
 *   - docs/guide/how-it-works.md
 *   - docs/guide/commands.md
 *   - docs/public/llms.txt (AI tool discovery)
 *   - docs/public/llms-full.txt (full content for AI tools)
 */

import { execFileSync } from "node:child_process";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "..");
const README_PATH = resolve(ROOT, "README.md");
const DOCS_DIR = resolve(ROOT, "docs");
const GUIDE_DIR = resolve(DOCS_DIR, "guide");
const PUBLIC_DIR = resolve(DOCS_DIR, "public");

const SITE_URL = "https://tktcorporation.github.io/ziku";

/** README のマーカーで区切られたセクションを抽出する */
function extractSection(readme: string, startMarker: string, endMarker: string): string {
  const startIndex = readme.indexOf(startMarker);
  const endIndex = readme.indexOf(endMarker);
  if (startIndex === -1 || endIndex === -1) return "";
  return readme.slice(startIndex + startMarker.length, endIndex).trim();
}

/** ## を # に、### を ## に変換する（README の見出しレベルをページ用に調整） */
function promoteHeadings(content: string): string {
  return content.replaceAll(
    /^(#{2,6}) /gm,
    (_, hashes: string) => `${"#".repeat(hashes.length - 1)} `,
  );
}

/**
 * README 内のリンクを VitePress のパスに変換する。
 * 例: docs/architecture/file-lifecycle.md → /architecture/file-lifecycle
 */
function fixLinks(content: string): string {
  // Markdown リンク構文内の .md 拡張子のみ除去する（コードブロック等の誤置換を防止）
  return content.replaceAll("](docs/", "](/").replaceAll(/(\]\([^)]*?)\.md(\))/g, "$1$2");
}

/**
 * ランディングページを生成する。
 *
 * ScrollLanding コンポーネントでスクロール同期アニメーションを提供するため、
 * VitePress デフォルトの home レイアウトではなく page レイアウトを使用する。
 */
function generateIndexPage(_readme: string): string {
  return `---
# This file is auto-generated by scripts/generate-site.ts — do not edit directly.
layout: page
title: ziku — Bi-directional template sync
sidebar: false
---

<ScrollLanding>

<!-- SSR フォールバック: client hydration 前にクローラー/no-JS 環境で表示される -->
<div style="text-align:center;padding:4rem 2rem;max-width:700px;margin:0 auto">

# ziku

Bi-directional template sync. Push improvements back, pull updates forward — with structure-aware 3-way merge.

\\\`\\\`\\\`bash
npx ziku setup
\\\`\\\`\\\`

[Get Started](/guide/getting-started) | [GitHub](https://github.com/tktcorporation/ziku)

</div>

</ScrollLanding>
`;
}

/** Getting Started ガイドページを生成する */
function generateGettingStartedPage(readme: string): string {
  const section = extractSection(
    readme,
    "<!-- GETTING_STARTED:START -->",
    "<!-- GETTING_STARTED:END -->",
  );
  return `---
# This file is auto-generated by scripts/generate-site.ts — do not edit directly.
---

${fixLinks(promoteHeadings(section))}
`;
}

/** How it Works ページを生成する */
function generateHowItWorksPage(readme: string): string {
  const section = extractSection(readme, "<!-- FEATURES:START -->", "<!-- FEATURES:END -->");
  // /architecture/file-lifecycle は日本語のみのため、英語サイトからはリンクを除外
  const cleaned = fixLinks(promoteHeadings(section)).replaceAll(
    /^>.*\[File Lifecycle\].*\n?/gm,
    "",
  );
  return `---
# This file is auto-generated by scripts/generate-site.ts — do not edit directly.
---

${cleaned}
`;
}

/** Commands リファレンスページを生成する */
function generateCommandsPage(readme: string): string {
  const section = extractSection(readme, "<!-- COMMANDS:START -->", "<!-- COMMANDS:END -->");
  // FILES セクションも追加
  const filesSection = extractSection(readme, "<!-- FILES:START -->", "<!-- FILES:END -->");
  return `---
# This file is auto-generated by scripts/generate-site.ts — do not edit directly.
---

${fixLinks(promoteHeadings(section))}

${fixLinks(promoteHeadings(filesSection))}
`;
}

/**
 * llms.txt を生成する（AI ツールがサイト内容を効率的に把握するための標準仕様）
 *
 * 仕様: https://llmstxt.org/
 */
function generateLlmsTxt(): string {
  return `# ziku

> A bi-directional dev environment template that evolves with you.

ziku is a CLI tool that syncs dev environment configuration files (CI workflows, linter configs, editor settings, etc.) between a template repository and multiple projects — bi-directionally.

## Docs

- [Getting Started](${SITE_URL}/guide/getting-started): How to set up and use ziku
- [How it Works](${SITE_URL}/guide/how-it-works): Architecture and design
- [Commands](${SITE_URL}/guide/commands): CLI command reference


## Links

- [GitHub](https://github.com/tktcorporation/ziku)
- [npm](https://www.npmjs.com/package/ziku)
- [Changelog](https://github.com/tktcorporation/ziku/blob/main/CHANGELOG.md)

## Optional

- [Full content](${SITE_URL}/llms-full.txt): Complete documentation for LLM context
`;
}

/** llms-full.txt を生成する（全ドキュメント内容をまとめたもの） */
function generateLlmsFullTxt(readme: string): string {
  // README のマークダウンをそのまま使う（画像バッジ部分を除く）
  const cleanedReadme = readme
    .replace(/<p align="center">[\s\S]*?<\/p>/m, "")
    .replace(/^> _ziku_.*$/m, "")
    .trim();

  return `# ziku — Full Documentation

> A bi-directional dev environment template that evolves with you.

${cleanedReadme}

---

## Installation

\`\`\`bash
npx ziku
\`\`\`

Or install globally:

\`\`\`bash
npm install -g ziku
\`\`\`

## Links

- GitHub: https://github.com/tktcorporation/ziku
- npm: https://www.npmjs.com/package/ziku
- License: MIT
`;
}

/**
 * ファイルを書き込み、フォーマッタを適用し、正規化された内容を返す。
 *
 * generate-readme.ts と同じパターン: write → format → read back canonical form。
 * これにより、生成スクリプトとフォーマッタの出力が常に一致する。
 */
async function writeAndFormat(filePath: string, content: string): Promise<string> {
  await writeFile(filePath, content);
  try {
    execFileSync("pnpm", ["oxfmt", "--write", filePath], { stdio: "ignore" });
  } catch {
    // oxfmt がサポートしない形式（.txt）は無視
  }
  return readFile(filePath, "utf-8");
}

/** メイン処理 */
async function main(): Promise<void> {
  const isCheck = process.argv.includes("--check");

  console.log("📄 Generating site pages...\n");

  await mkdir(GUIDE_DIR, { recursive: true });
  await mkdir(PUBLIC_DIR, { recursive: true });

  const readme = await readFile(README_PATH, "utf-8");

  // 生成するファイルのマップ
  const files: Record<string, string> = {
    [resolve(DOCS_DIR, "index.md")]: generateIndexPage(readme),
    [resolve(GUIDE_DIR, "getting-started.md")]: generateGettingStartedPage(readme),
    [resolve(GUIDE_DIR, "how-it-works.md")]: generateHowItWorksPage(readme),
    [resolve(GUIDE_DIR, "commands.md")]: generateCommandsPage(readme),
    [resolve(PUBLIC_DIR, "llms.txt")]: generateLlmsTxt(),
    [resolve(PUBLIC_DIR, "llms-full.txt")]: generateLlmsFullTxt(readme),
  };

  // 既存の内容を保存（check モードで復元するため）
  const originals: Record<string, string> = {};
  for (const filePath of Object.keys(files)) {
    try {
      originals[filePath] = await readFile(filePath, "utf-8");
    } catch {
      originals[filePath] = "";
    }
  }

  // write → format → read back で正規化された内容を取得
  const canonical: Record<string, string> = {};
  for (const [filePath, content] of Object.entries(files)) {
    canonical[filePath] = await writeAndFormat(filePath, content);
  }

  // 差分を検出
  const outdated: string[] = [];
  for (const filePath of Object.keys(files)) {
    if (originals[filePath] !== canonical[filePath]) {
      outdated.push(filePath.replace(`${ROOT}/`, ""));
    }
  }

  if (isCheck) {
    // check モードでは元のファイルを復元する。
    // writeAndFormat が書き込んだ一時ファイルを確実にクリーンアップするため、
    // 元が空（= ファイルが存在しなかった）なら削除する。
    for (const [filePath, original] of Object.entries(originals)) {
      if (original) {
        await writeFile(filePath, original);
      } else {
        await rm(filePath, { force: true });
      }
    }

    if (outdated.length > 0) {
      for (const path of outdated) {
        console.error(`  - ${path} is out of date`);
      }
      console.error("\n❌ Site pages are out of date.");
      console.error("   Run `pnpm run site:generate` to update.\n");
      process.exit(1);
    }
    console.log("\n✅ Site pages are up to date.\n");
    return;
  }

  // 更新されたファイルを報告
  if (outdated.length > 0) {
    for (const path of outdated) {
      console.log(`  ✅ ${path} updated.`);
    }
  } else {
    console.log("\n✅ Site pages are already up to date.\n");
  }
}

main().catch((error: unknown) => {
  console.error("Error:", error instanceof Error ? error.message : String(error));
  process.exit(1);
});
